language: cpp
before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update  -qq
- sudo apt-get install -qq qtbase5-dev qtbase5-dev-tools qttools5-dev-tools
- sudo apt-get install -qq libqt5x11extras5-dev
- sudo apt-get install -qq libjack-dev libasound2-dev
before_script:
- ./autogen.sh
